Description of forward
Home > Functions > subfunctions > forward.m
forward
PURPOSE
r = forward (q,L)
SYNOPSIS
function r = forward (q, L)
DESCRIPTION
 r = forward (q,L)
 Forward kinematic simulation
 Input:
   q               Joint state variable
   L               Link length
 Output:
   r               Task space variable
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generate_data_ccl data = generate_alpha_ccl (settings)
return_lambda lambda = return_lambda(q,L)
visualise_sbs SbS_vis (settings)
SOURCE CODE
function r = forward (q, L)
% r = forward (q,L)
% Forward kinematic simulation
% Input:
%   q               Joint state variable
%   L               Link length
% Output:
%   r               Task space variable
r    = zeros(2,1) ;
r(1) = L(1)*cos(q(1,:)) + L(2)*cos(q(1,:)+q(2,:)) ;
r(2) = L(1)*sin(q(1,:)) + L(2)*sin(q(1,:)+q(2,:)) ;
end