Description of get_rotation_matrix
Home > Functions > subfunctions > get_rotation_matrix.m
get_rotation_matrix
PURPOSE
R = get_rotation_matrix(theta_k, current_Rn, search, alpha_id)
SYNOPSIS
function R = get_rotation_matrix(theta_k, current_Rn, search, alpha_id)
DESCRIPTION
 R = get_rotation_matrix(theta_k, current_Rn, search, alpha_id)
 Calculate rotation matrix after finding the k^th constraint vector.
 The result is rotation matrix that rotate vectors into a space orthogonal to all constraint vectors
 Input:
   theta_k                               Theta from kth constrains
   current_Rn                            Rotation matrix from the last iteration
   search                                Dimensionality related searching parameters
   alpha_id                              Current searching dimension of alpha
 Output:
   R                                     Rotation matrix
CROSS-REFERENCE INFORMATION
This function calls:
make_givens_matrix G = make_givens_matrix(dim, i, j, theta)
This function is called by:
learn_alpha_ccl [optimal] = learn_alpha_ccl (Un, X, options)
learn_lambda_ccl [optimal] = learn_lambda_ccl (Un, X, J, options)
predict_proj_alpha N = predict_proj (model, q, Iu)
predict_proj_lambda N = predict_proj (model, q, Iu)
SOURCE CODE
function R = get_rotation_matrix(theta_k, current_Rn, search, alpha_id)
% R = get_rotation_matrix(theta_k, current_Rn, search, alpha_id)
%
% Calculate rotation matrix after finding the k^th constraint vector.
% The result is rotation matrix that rotate vectors into a space orthogonal to all constraint vectors
%
% Input:
%   theta_k                               Theta from kth constrains
%   current_Rn                            Rotation matrix from the last iteration
%   search                                Dimensionality related searching parameters
%   alpha_id                              Current searching dimension of alpha
%
% Output:
%   R                                     Rotation matrix
R = eye(search.dim_u) ;
for d = alpha_id : search.dim_t
    R = R * make_givens_matrix(search.dim_u, d, d+1, theta_k(d) )' ;
end
R = R * current_Rn ;
end