Description of get_unit_vector_from_matrix
Home > Functions > subfunctions > get_unit_vector_from_matrix.m
get_unit_vector_from_matrix
PURPOSE
alpha = get_unit_vector_from_matrix (Theta)
SYNOPSIS
function alpha = get_unit_vector_from_matrix (Theta)
DESCRIPTION
 alpha = get_unit_vector_from_matrix (Theta)
 Convert constraint parameters to constraint vectors e.g. for 3D problem
 a1 = cos(theta1)
 a2 = sin(theta1)*cos(theta2)
 a3 = sin(theta1)*sin(theta2)
 a = [a1,a2,a3]'
 Input:
   Theta                                 Learnt constraint parameters
 Output:
   alpha                                 A unit vector of constraint basis
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generate_search_space search = generate_search_space (search)
predict_proj_alpha N = predict_proj (model, q, Iu)
predict_proj_lambda N = predict_proj (model, q, Iu)
set_obj_AUn [fun] = obj_AUn (model, W, BX, RnUn)
SOURCE CODE
function alpha = get_unit_vector_from_matrix (Theta)
% alpha = get_unit_vector_from_matrix (Theta)
%
% Convert constraint parameters to constraint vectors e.g. for 3D problem
% a1 = cos(theta1)
% a2 = sin(theta1)*cos(theta2)
% a3 = sin(theta1)*sin(theta2)
% a = [a1,a2,a3]'
%
% Input:
%   Theta                                 Learnt constraint parameters
%
% Output:
%   alpha                                 A unit vector of constraint basis
[dim_n dim_t]   = size(Theta) ;
alpha           = zeros(dim_n,dim_t+1) ;
alpha(:,1)      = cos(Theta(:,1)) ;
for i =2:dim_t
    alpha(:,i) = cos(Theta(:,i)) ;
    for k = 1:i-1
        alpha(:,i) = alpha(:,i) .* sin(Theta(:,k)) ;
    end
end
alpha(:,dim_t+1)    = ones(dim_n,1) ;
for k = 1:dim_t
    alpha(:,dim_t+1) = alpha(:,dim_t+1) .* sin(Theta(:,k)) ;
end
end