Description of jacobian
Home > Functions > subfunctions > jacobian.m
jacobian
PURPOSE
J = jacobian (q,L)
SYNOPSIS
function J = jacobian (q, L)
DESCRIPTION
 J = jacobian (q,L)
 Jacobian calculation
 Input:
   q               Joint state variable
   L               Link length
 Output:
   J               Jacobian
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generate_data_ccl data = generate_alpha_ccl (settings)
demo_2_link_arm demo_2_link_arm
visualise_sbs SbS_vis (settings)
SOURCE CODE
function J = jacobian (q, L)
% J = jacobian (q,L)
% Jacobian calculation
% Input:
%   q               Joint state variable
%   L               Link length
% Output:
%   J               Jacobian
J(1,1) = -L(1)*sin(q(1,:)) - L(2)*sin(q(1,:)+q(2,:)) ;
J(1,2) =                   - L(2)*sin(q(1,:)+q(2,:)) ;
J(2,1) =  L(1)*cos(q(1,:)) + L(2)*cos(q(1,:)+q(2,:)) ;
J(2,2) =                     L(2)*cos(q(1,:)+q(2,:)) ;
end