Description of plotCircle3D
Home > Functions > subfunctions > plotCircle3D.m
plotCircle3D
PURPOSE
SYNOPSIS
function plotCircle3D(center,radius,normal)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
generate_data_kuka_wiping Generates states (robot joint positions) and actions (robot joint velocities)
test Generates states (robot joint positions) and actions (robot joint velocities)
demo_kuka_wiping Given the data composed of states - joint positions - and actions - joint
SOURCE CODE
function plotCircle3D(center,radius,normal)
theta=0:0.01:2*pi;
v=null(normal.');
points=repmat(center,1,size(theta,2))+radius*(v(:,1)*cos(theta)+v(:,2)*sin(theta));
plot3(points(1,:),points(2,:),points(3,:),'r-');
end